version: '3.7'

services:
  transfer-server:
    container_name: transfer-server
    image: node:12-alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    command: npm start
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - transfer-server-postgres
      - transfer-server-redis
  transfer-server-redis:
    container_name: transfer-server-redis
    image: redis:5
    networks:
      - webnet
  transfer-server-postgres:
    container_name: transfer-server-postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: transfer-server
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
