version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - run: cp .circleci/algo.d.ts node_modules/bitgo/dist/types/src/v2/coins/algo.d.ts
      - run: npm run build
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ .Branch }}-{{ checksum "package-lock.json" }}

      # Run tests
      - run: npm run test -- --no-watch --no-progress
      - persist_to_workspace:
          root: ~/project
          paths: ./*
