version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - run: npm run build
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ .Branch }}-{{ checksum "package-lock.json" }}

      # Run tests
      - run: npm run test:cov -- --no-watch --no-progress
      - sonarcloud/scan
      - persist_to_workspace:
          root: ~/project
          paths: ./*

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: SONAR_TOKEN
